version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: personal_finance
      POSTGRES_PASSWORD: personal_finance_password
      POSTGRES_DB: personal_finance_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
